# -*- coding: utf-8 -*-
"""wordcloud.ipynb

Automatically generated by Colaboratory.

"""

import numpy as np
import pandas as pd
from os import path
from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
import matplotlib.pyplot as plt

data = pd.read_excel("Data4700 Americorp SDOH Data.xlsx")
data.head(3)

sdoh = data['SDOH Screening'].to_list()
sdoh = list(filter(lambda x: x!= 'na', sdoh))
text = ' '.join([str(string) for string in sdoh])

wordcloud = WordCloud(min_font_size=8, max_font_size=90,
                      height=400, width=800).generate(text)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

inter = data['Information on Interaction'].to_list()
inter = list(filter(lambda x: x!= 'na', inter))
text2 = ' '.join([str(string) for string in inter])

wordcloud = WordCloud(min_font_size=8, max_font_size=90,
                      height=400, width=800).generate(text2)
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()
